# Generated by Django 4.2.2 on 2023-07-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('i', 'Installing'), ('r', 'Running'), ('s', 'Stopped'), ('e', 'Error')], default='i', max_length=1)),
                ('os', models.CharField(choices=[('ub', 'Ubuntu'), ('co', 'CentOS')], default='ub', max_length=2)),
                ('os_version', models.CharField(choices=[('ub 22', '22.04 (LTS) x64'), ('ub 20', '20.04 (LTS) x64'), ('ub 16', '16.04 (LTS) x64'), ('co 9', '9 Stream x64'), ('co 8', '8 Stream x64')], default='ub 16', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
