# Generated by Django 4.2.2 on 2023-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os',
            field=models.CharField(choices=[('ub', 'Ubuntu'), ('co', 'CentOS')], max_length=2),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(choices=[('ub 22', '22.04 (LTS) x64'), ('ub 20', '20.04 (LTS) x64'), ('ub 16', '16.04 (LTS) x64'), ('co 9', '9 Stream x64'), ('co 8', '8 Stream x64')], max_length=5),
        ),
    ]
