# Generated by Django 4.2.2 on 2023-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_server_os_alter_server_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='container',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(choices=[('ub-22', '22.04 (LTS) x64'), ('ub-20', '20.04 (LTS) x64'), ('ub-16', '16.04 (LTS) x64'), ('co-9', '9 Stream x64'), ('co-8', '8 Stream x64')], max_length=5),
        ),
    ]
